In [1]:
# import
import numpy as np

## Q1. Create a 1-dimensional NumPy array of numbers from 1 to 10 and print it.

In [2]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Q2. Create a 2-dimensional NumPy array of shape (3,3) with numbers from 1 to 9 and print it.

In [3]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Q3. Using the 1-dimensional array from Q1, extract elements from index 2 to 6 and print them.

In [4]:
a[2:7]

array([3, 4, 5, 6, 7])

## Q4. Using the same array from Q1, extract every 2nd element and print it.

In [5]:
a[0:10:2]

array([1, 3, 5, 7, 9])

## Q5. Create a 1-dimensional array of 12 numbers and reshape it into a 3x4 array. Print the reshaped array.

In [6]:
c=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
d=c.reshape(3,4)

In [7]:
d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## Q6. Create two arrays: a = [1,2,3,4] and b = [5,6,7,8]. Perform addition, subtraction, multiplication, and division on them.

In [8]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [9]:
np.add(a,b)

array([ 6,  8, 10, 12])

In [10]:
np.subtract(a,b)

array([-4, -4, -4, -4])

In [11]:
np.multiply(a,b)

array([ 5, 12, 21, 32])

In [12]:
np.divide(a,b)

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

## Q7. Create a 3x3 array with numbers from 1 to 9. Find the sum, mean, maximum, and minimum of the array.

In [13]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [14]:
np.sum(a)

45

In [15]:
np.mean(a)

5.0

In [16]:
np.max(a)

9

In [17]:
np.min(a)

1

## Q8. From the same 3x3 array, extract all elements greater than 5.

In [18]:
a[a>5]

array([6, 7, 8, 9])

## Q9. Create a 5x5 array with numbers from 1 to 25. Extract the middle 3x3 sub-array.

In [19]:
e=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25])
f=e.reshape(5,5)
f

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [20]:
f[1:4,1:4]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

## Q10. Flatten the 3x4 array from Q5 into a 1-dimensional array and print it.

In [21]:
d.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])